language: generic
services:
 - docker
before_install: 
  - "docker build -t darahumadac/reactapp -f ./docker/reactapp/client/Dockerfile.dev ./docker/reactapp/client"
script: 
  - "docker run -e CI=true darahumadac/reactapp npm run test -- --coverage"